

const mongoose = require('mongoose');
const bcrypt = require("bcrypt");



// Membership type codes used in Membership Number (MN)
const MEMBERSHIP_CODES = {
    regular: "R",
    premium: "P",
    temporary: "T"
};

// Uganda NIN Format: Example C12345678X
const ugNinRegex = /^[A-Z]{1}[0-9]{8}[A-Z]{1}$/;

// Uganda Phone (MTN/Airtel): +2567XXXXXXXX or 07XXXXXXXX
const ugPhoneRegex = /^(\+256|0)7[0-9]{8}$/;

const userSchema = new mongoose.Schema({

    // AUTOGENERATED — user does not enter this
    membershipNumber: {
        type: String,
        unique: true
    },

    firstName: {
        type: String,
        required: true,
        trim: true
    },

    lastName: {
        type: String,
        required: true,
        trim: true
    },

    password: {
        type: String,
        required: true,
        minlength: 8
    },

    dob: {
        type: Date,
        required: true
    },

    gender: {
        type: String,
        enum: ["Male", "Female"],
        required: true
    },

    membershipType: {
        type: String,
        enum: ["regular", "premium", "temporary"],
        required: true
    },

    nin: {
        type: String,
        required: true,
        unique: true,
        validate: {
            validator: (value) => ugNinRegex.test(value),
            message: "Invalid NIN number"
        }
    },

    phoneNumber: {
        type: String,
        required: true,
        validate: {
            validator: (value) => ugPhoneRegex.test(value),
            message: "Invalid Phone number"
        }
    },

    occupation: {
        type: String,
        default: ""
    },

    address: {
        district: { type: String },
        county: { type: String },
        subcounty: { type: String },
        parish: { type: String },
        village: { type: String }
    },

    nextOfKin: {
        name: { type: String, required: true },
        relationship: { type: String, required: true },
        phone: { 
            type: String, 
            required: true,
            validate: {
                validator: (value) => ugPhoneRegex.test(value),
                message: "Invalid Ugandan phone number for next of kin."
            }
        }
    },

    dateCreated: {
        type: Date,
        default: Date.now
    }
});


// -----------------------------------------------------
// AUTO-GENERATE MEMBERSHIP NUMBER (MN)
// Format: AO1125R007M
// -----------------------------------------------------
userSchema.pre("save", async function (next) {
    if (!this.isNew) return next(); // Only for new users

    const User = mongoose.model("User");

    // count existing documents to build sequential index
    const count = await User.countDocuments() + 1;

    const firstCharLast = this.lastName.charAt(0).toUpperCase();
    const firstCharFirst = this.firstName.charAt(0).toUpperCase();

    const month = String(this.dateCreated.getMonth() + 1).padStart(2, "0");
    const year = String(this.dateCreated.getFullYear()).slice(-2);

    const membershipCode = MEMBERSHIP_CODES[this.membershipType];
    const index = String(count).padStart(3, "0"); // e.g. 001

    // Final format
    this.membershipNumber = 
        `${firstCharLast}${firstCharFirst}${month}${year}${membershipCode}${index}`;

    next();
});


// -----------------------------------------------------
// HASH PASSWORD BEFORE SAVING
// -----------------------------------------------------
userSchema.pre("save", async function (next) {
    if (!this.isModified("password")) return next();

    const salt = await bcrypt.genSalt(10);
    this.password = await bcrypt.hash(this.password, salt);

    next();
});


userSchema.methods.comparePassword = async function (enteredPassword) {
    return await bcrypt.compare(enteredPassword, this.password);
};


const purchaseRequisitionSchema = new mongoose.Schema({
    id : {
        type: String,
        required: [true, "please the id is required"],
        unique: true
    }, 
    pr_number : {
        type: Number,
        defauld: 0
    },
    pr_date: {
        type: Date,
        required: [true, "Please the pr_date required"],
    },
    pr_amout: {
        type: Number,
        required: [true, "  Please the amount is required"]
    }, 
    pr_department: {
        type: String,
        required: [true, "Please the department is required"]
    },
    pr_approval_name:{
        type: String,
        required: [true, "please the approval name is required"]
    }, 
    pr_approval_date : {
        type: Date,
        default: Date.now
    }
})

const PurchaseOrderSchema = new mongoose.Schema({ 

    id : {
        type: String,
        required: [true, "The id is required"],
        unique: true
    },

    po_number :{
        type: Number,
        required: [true, "the  order number is required"],
        unique: true
    },
    po_date: {
        type: Date,
        required: [true, "The order date is required"]

    },
    po_amout : {
        type: Number,
        required: [true, "Please the amount is required"]
    },
    po_department: {
        type: String,
        required: [true, "Please the department is requred"]
    },

    po_approval_name : {
        type: String,
        required: [true, "The approval name is rquired"]
    },
    po_approval_date: {
        type: Date,
        default: Date.now
    }
})






const user = mongoose.model("User", userSchema);
const purchaseRequisition = mongoose.model("PurchaseRequisition", purchaseRequisitionSchema);
const PurchaseOrder = mongoose.model("PurchaseOrder", PurchaseOrderSchema)




module.exports = {
    user,
    purchaseRequisition,
    PurchaseOrder
}
